---
title: "Gov 50 Final Project"
author: "Max Murphy"
description: "Forecasting Violent Conflict"
output:
  distill::distill_article:
    self_contained: false
---



## Proposal

Should we expect the effects of climate change to increase the frequency of violent conflicts? There is a growing concern that as weather patterns become more extreme and unpredictable, there will be a concomitant increase in violent conflict, namely civil war. However, what remains unclear is whether there have already been violent conflicts that have been fueled by climate change. As such, in this paper I will interrogate the relationship between changes in temperature and precipitation and violent conflict in Sudan between 1997 and 2021. The reason for the focus on temperature and precipitation change is because these are both likely to become more inconstant due to climate change, and the rationale behind analyzing these effects in Sudan is because the civil war in Sudan has been dubbed “the first climate change conflict” (World Food Program USA, 2017). My hypothesis is that an increase in temperature and a decrease in precipitation will be correlated with higher rates of violent conflict in Sudan. Given that much of Sudan’s population is dependent upon rain-fed farming, it follows that in drier and warmer periods might lead to economic stress - and economic welfare is one of the most strongly correlated factors with violent conflict. The two explanatory variables - which are observed annual mean temperature per year and observed annual precipitation per year, respectively - are both taken from the Climatic Research Unit (CRU) of University of East Anglia. Meanwhile, using data from ACLED, the outcome variable is the number of fatalities from battles, protests, riots, violence against civilians, and explosions/remove violence each year. If the number of fatalities is higher in the years that have higher average temperatures and lower average precipitation levels, this would lend support to my hypothesis. Conversely, if fatality levels are not correlated with a change in temperature or precipitation, then this would provide evidence against my hypothesis.

